mode: 'train'
ARCHITECTURE:
    name: 'ResNet50_vd'

checkpoints: ""
pretrained_model: "D:/computercode/python/PaddleClas/pre_model/ResNet50_vd_pretrained.tar"
model_save_dir: "./output/"
classes_num: 4
total_images: 17117
save_interval: 20
validate: True
valid_interval: 1
epochs: 100
topk: 5
image_shape: [3, 224, 224]

LEARNING_RATE:
    function: 'Cosine'          
    params:                   
        lr: 0.0125

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.00001

TRAIN:
    batch_size: 2
    num_workers: 1
    file_list: "D:/computercode/python/PaddleClas/dataset/cassava-leaf-disease-classification/train_list.txt"
    data_dir: "D:/computercode/python/PaddleClas/dataset/cassava-leaf-disease-classification/train_images/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

VALID:
    batch_size: 2
    num_workers: 1
    file_list: "D:/computercode/python/PaddleClas/dataset/cassava-leaf-disease-classification/val_list.txt"
    data_dir: "D:/computercode/python/PaddleClas/dataset/cassava-leaf-disease-classification/train_images/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
